language: cpp

os: linux

addons:
  - apt:
    - sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    - packages:
      - g++-8
      - clang-6.0

env:
  - CC=gcc-8 CXX=g++-8
  - CC=clang-6.0 CXX=clang++-6.0

script:
  - ./scripts/test.sh Debug
  - ./scripts/test.sh Release
  - ./scripts/benchmark.sh

